name: Docker

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        target_arch: [arm, i386]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: windows-ce-build-environment-${{ matrix.target_arch }}
        registry: ghcr.io
        buildArgs: target_arch=${{ matrix.target_arch }}
        addLatest: true
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
